name: Common (Build Docker Image)

on: 
  workflow_call:
    inputs:
      image_tag:
        type: string
        required: true

jobs:
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get repository name
        id: repo-name
        uses: MariachiBear/get-repo-name-action@v1.1.0
        with:
          string-case: 'lowercase'

      # Start AWS environment
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      # End AWS environment

      - name: Build, tag, and push image
        id: build-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ steps.repo-name.outputs.repository-name }}
          ENVIRONMENT_IMAGE_TAG: ${{ inputs.image_tag }}
          GIT_HASH_IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$ECR_REPOSITORY:$GIT_HASH_IMAGE_TAG -t $REGISTRY/$ECR_REPOSITORY:$ENVIRONMENT_IMAGE_TAG --target production .
          docker push $REGISTRY/$ECR_REPOSITORY:$ENVIRONMENT_IMAGE_TAG