name: Configure the project from the template

on: 
  create

jobs:
  refactor-project-name:
    name: Refactor Project Name    
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/template'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get repository name
        id: repo-name
        uses: MariachiBear/get-repo-name-action@v1.1.0
        with:
          string-case: 'lowercase'
        
      - name: Run Refactor
        run: |
          git grep -l '${template.project_name}' | xargs sed -i 's/${template.project_name}/${{ steps.repo-name.outputs.repository-name }}/g'
          rm -f .github/workflows/configure-project-from-template.yml
          mv README.example.md README.md
      
      - name: Commit and push
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: template
          commit-message: 'Configure the project from the template'          
          name: Omega Energia
          email: developers@omegaenergia.com
      
      - name: Migrate
        uses: liyanchang/default-branch-migration@v1.0.1
        with:          
          github_token: ${{ secrets.GITHUB_TOKEN }}          
          previous_default: template
          new_default: main

      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{github.token}}
          branches: template

          
    