name: Production Pipeline

on: 
  release:
    types: [published]

jobs:
  test-and-quality:
    uses: ./.github/workflows/commom-test-and-quality.yml

  build-image:
    needs: [test-and-quality]     
    uses: ./.github/workflows/commom-docker-image-build.yml
    secrets: inherit
    with:
      image_tag: prod
  
  deploy:
    needs: [build-image]
    uses: ./.github/workflows/commom-aws-ecs-deploy.yml
    secrets: inherit
    with:
      environment: production
      environment_url: 
      image_tag: prod